### ISSUE TITLE
Maybe old data

### ISSUE THREAD

**Issue by ghost** [eraffaelli/GodotEngine-Resources#1]
![image](https://user-images.githubusercontent.com/17880848/52368210-e69a7a80-2a73-11e9-9990-5e692e1fb445.png)

**Comment by eraffaelli** [comment]
Oh, thanks. You're right it seems to have disappeared since I added it. I'm going to strikethrough it for a while in case it come back and if it don't for a moment I'll remove it. I'm going to check other in the next few day too.
